--- 
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - "docker build -t rajeshm9495/node-server ."
      - "docker tag rajeshm9495/node-server rajeshm9495/node-server:latest"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - "docker push rajeshm9495/node-server:latest"
  pre_build: 
    commands: 
      - "echo Logging in to Docker Hub..."
      - "docker login --username=\"rajeshm9495\" --password=\"password\""
version: 0.1

